<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8670b5d17a1618bed92275c3d55b4a3e
{
    public static $prefixLengthsPsr4 = array (
        'c' => 
        array (
            'codecourse\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'codecourse\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8670b5d17a1618bed92275c3d55b4a3e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8670b5d17a1618bed92275c3d55b4a3e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8670b5d17a1618bed92275c3d55b4a3e::$classMap;

        }, null, ClassLoader::class);
    }
}
